### ISSUE TITLE
std::string GetFullName() const

### ISSUE THREAD

**Issue by BossMode** [KN4CK3R/UnrealEngineSDKGenerator#10]
`std::string GetFullName() const
	{
		std::string name;
		if (Clazz != nullptr)
		{
			UClass* clazz2 = (UClass*)Clazz;
			std::string temp;
			for (UObject* p = Outer; p; p = p->Outer)
			{
				temp = p->GetName() + "." + temp;
			}
			name = clazz2->GetName();
			name += " ";
			name += temp;
			name += GetName();
		}
		return name;
	}`

Fails with `error C2227: left of '->GetName' must point to class/struct/union/generic type`

Same thing with IsA,
`	bool UObject::IsA(UClass* cmp) const
	{
		for (auto super = Clazz; super; super = (UClass*)super->SuperField)
		{
			if (super == cmp)
			{
				return true;
			}
		}
		return false;
	}`

class UObject looks like:

`class UObject
{
public:
	static FUObjectArray*                              GObjects;                                         		// 0x0000(0x0000)
	void*                                              Vtable;                                           		// 0x0000(0x0000) NOT AUTO-GENERATED PROPERTY
	int32_t                                            ObjectFlags;                                      		// 0x0000(0x0000) NOT AUTO-GENERATED PROPERTY
	int32_t                                            InternalIndex;                                    		// 0x0000(0x0000) NOT AUTO-GENERATED PROPERTY
	class UClass*                                      Clazz;                                            		// 0x0000(0x0000) NOT AUTO-GENERATED PROPERTY
	FName                                              Name;                                             		// 0x0000(0x0000) NOT AUTO-GENERATED PROPERTY
	class UObject*                                     Outer;                                            		// 0x0000(0x0000) NOT AUTO-GENERATED PROPERTY
....`

**Comment by BossMode** [comment]
Sorry. 

Generator created 	declaration of std::string GetFullName() const; in UObject class, it didn't defined that, do I need to add definition of the function manually or pass function pointer to the game's function UOBjectBaseUtility::GetFullName ?

**Comment by KN4CK3R** [comment]
But the generator doesn't name a variable "clazz" or something. Do you have a modified generator? Currently I don't really know what you are talking about. For which game is your code? Every (normal) generator has the GetName method as a predefined function, so this method can't be missing. (See every Generator.cpp in the Targer sub folder.)

**Comment by BossMode** [comment]
Nevermind, I didn't add .cpp files to my files. Just read whole "readme.txt"

New problem is that I cannot get global names past "CoreUObject"

```
void TestGNamesCrashesGame()
{
	for (int i = 0; i < 50; i++)
	{
		auto temp = Classes::FName::GetGlobalNames()[i];
		if (temp != nullptr)
		{
			std::string Name = temp->GetAnsiName();
			std::cout << Name << std::endl;
		}
	}
}

```

Outputs:
`None
ByteProperty
IntProperty
BoolProperty
FloatProperty
ObjectProperty
NameProperty
DelegateProperty
ClassProperty
ArrayProperty
StructProperty
VectorProperty
RotatorProperty
StrProperty
TextProperty
InterfaceProperty
MulticastDelegateProperty
WeakObjectProperty
LazyObjectProperty
AssetObjectProperty
UInt64Property
UInt32Property
UInt16Property
Int64Property
Int16Property
Int8Property
AssetSubclassOfProperty
MapProperty
SetProperty
Core
Engine
Editor
CoreUObject
`

Then it crashes, any idea why?

**Comment by KN4CK3R** [comment]
For which game is this?

**Comment by BossMode** [comment]
Nevermind. Your Generator works perfectly I just had to update some classes, all these previous issues were caused by my lack of knowledge regarding how exactly this SDK generator functions. It's all right after I digged into it.

**Comment by KN4CK3R** [comment]
Is there something I should explain better? I know my generator has more custom work as TheFeckless's generator but if you use a previous project as template there aren't much ToDos left.
