### ISSUE TITLE
Package::packageOrder doesn't update if a package has only constants or enums

### ISSUE THREAD

**Issue by kokole** [KN4CK3R/UnrealEngineSDKGenerator#12]
Code that updates packageOrder should be copied to Package::GenerateConst and Package::GenerateEnum too.

**Comment by KN4CK3R** [comment]
Why? Because of #11 ? Never have seen a dependency for constants or enums.

**Comment by kokole** [comment]
PLAYERUNKNOWN'S BATTLEGROUNDS has package that contains an enum only (KeyState).
I'm not sure if packages are generated correctly because I get lots of them. SDK works nicely though.
