### ISSUE TITLE
rocket update

### ISSUE THREAD

**Issue by DopeHax** [KN4CK3R/UnrealEngineSDKGenerator#14]
can you please update the sdk? it's 1.33 now sry for requesting it.
also the dump doesn't get the full object list
and sry again for being selfish

**Comment by KN4CK3R** [comment]
You can't fix it yourself and update the classes here or you don't want to make it? ;) Can't look at it at the moment.

**Comment by DopeHax** [comment]
idk if the classes got updated, but i can't find the right objects for playercontrolelr and ball.
http://prntscr.com/f0d5wv
Also im kinda new to hooking in ue4 postrender etc.. i've managed to hook processevent.
But for drawing as i understood i have to call my own postrender with my drawing stuff.
For e.g i've used that one  http://prntscr.com/f0d6mr
And how i call http://prntscr.com/f0d9e0

**Comment by rmadair** [comment]
@DopeHax Hop in IRC, I'm happy to answer a few of these questions. For starters:

- It's UE3, not UE4
- Look for other "Transient..._TA_#" classes, not the "Default__" ones

**Comment by DopeHax** [comment]
what u meant by hop in irc?
also have u tried to draw on rocket league using processevent hook?

**Comment by MagesRL** [comment]
@DopeHax did you manage to get it to work?

**Comment by wa7err** [comment]
@MagesRL Can't make sdk work too. Getting nullptr for Gobjects and Gnames

**Comment by KN4CK3R** [comment]
If GObjects and GNames are both nullptr, the sigs are not working anymore.

**Comment by wa7err** [comment]
@KN4CK3R Any solutions?

**Comment by KN4CK3R** [comment]
The sigs are still working. Someone told me to disable Windows Defender which may cause a problem. Don't know if that helps. Otherwise debug your code and find the error. Works fine from here.

**Comment by wa7err** [comment]
@KN4CK3R Is it ok that I have `TArray<FNameEntry*>* FName::GNames = nullptr;
	TArray<UObject*>* UObject::GObjects = nullptr; ` in RL_basic ?

**Comment by KN4CK3R** [comment]
Thats correct.

**Comment by wa7err** [comment]
Is there any examples on how to use your SDK?

**Comment by KN4CK3R** [comment]
every public UE game hack is your example
