### ISSUE TITLE
Paragon

### ISSUE THREAD

**Issue by ImVexed** [KN4CK3R/UnrealEngineSDKGenerator#15]
Paragon port isn't working, the ObjectStore Initialize is failing, maybe the signature is out of date? There have been some fairly large updates as of late. How would you recommend updating the sig's in the future?

**Comment by KN4CK3R** [comment]
If the sig is broken someone must provide a new signature. The is no other recommend way. ;) If you find a working sig, make a pull request and I will merge the changes.

**Comment by iFamiliar** [comment]
In general, how would you update the signature? Is there a guide available which you used to find the signatures (before game updates breaking the signatures).

**Comment by KN4CK3R** [comment]
An dumb but easy way is to save the current exe with the working sig. If the sig stops working search for the same memory region in the new exe and make a new sig.

**Comment by ImVexed** [comment]
What offset does it need in general? What does the offset point to in the first place?

**Comment by KN4CK3R** [comment]
As you can see in the code you need sigs for UObjects, UNames and ProcessEvent

**Comment by iFamiliar** [comment]
Thanks for responding, now I will know for the future.

Can't update any sigs by myself without the pre-update exe to compare to.
If I do figure out how to update them, I will certainly send you the signatures.

**Comment by KN4CK3R** [comment]
In the UE3 tutorial from The Feckless are some basic infos about the sigs. But he just uses the same sigs for every game. So if they break you are lost. ;)

https://www.youtube.com/watch?v=yNe4jz1v0R4
