### ISSUE TITLE
Update FORTNITE Offsets

### ISSUE THREAD

**Issue by formatme** [KN4CK3R/UnrealEngineSDKGenerator#17]
They are out of date im pretty sure

**Comment by KN4CK3R** [comment]
Then please update them and create a pull request. :-)

**Comment by ApocDev** [comment]
Cba to fork and PR, but UProperty changed.

`class UProperty : public UField
{
public:
	__int32 ArrayDim; //0x0030 
	__int32 ElementSize; //0x0034 
	FQWord PropertyFlags; //0x0038
	__int32 PropertySize; //0x0040 
	__int32 Offset; //0x0044 
	char pad_0x0044[0x28]; //0x0050
};`

Then the patterns:
`bool ObjectsStore::Initialize()
{
	auto address = FindPattern(GetModuleHandleW(L"FortniteClient-Win64-Shipping.exe"), reinterpret_cast<const unsigned char*>("\x48\x8D\x05\x00\x00\x00\x00\x48\x89\x01\x33\xC9\x84\xD2\x41\x8B\x40\x08\x49\x89\x48\x10\x0F\x45\x05\x00\x00\x00\x00\xFF\xC0\x49\x89\x48\x10\x41\x89\x40\x08"), "xxx????xxxxxxxxxxxxxxxxxx????xxxxxxxxxx");`

`auto address = FindPattern(GetModuleHandleW(L"FortniteClient-Win64-Shipping.exe"), reinterpret_cast<const unsigned char*>("\x48\x89\x1D\x00\x00\x00\x00\x48\x8B\x5C\x24\x00\x48\x83\xC4\x28\xC3\x48\x8B\x5C\x24\x00\x48\x89\x05\x00\x00\x00\x00\x48\x83\xC4\x28\xC3"), "xxx????xxxx?xxxxxxxxx?xxx????xxxxx");`

**Comment by KN4CK3R** [comment]
Fixed with 0bbff1a.
