### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by winocreative** [KN4CK3R/UnrealEngineSDKGenerator#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C3779	'cpplinq::detail::where_range<TRange,TPredicate>::operator >>': a function that returns 'auto' cannot be used before it is defined	UnrealEngine4	D:\SDK_GEN\Engine\Main.cpp	106	

	for (auto&& s : missing >> select([](auto&& kv) { return kv.first.Cast<UEStruct>(); }) >> experimental::container()) << why this is error?
		{
			os2 << "// " << s.GetFullName() << "\n// ";
			os2 << tfm::format("0x%04X\n", s.GetPropertySize());

			os2 << "struct " << MakeValidName(s.GetNameCPP()) << "\n{\n";
			os2 << "\tunsigned char UnknownData[0x" << tfm::format("%X", s.GetPropertySize()) << "];\n};\n\n";
		}

**Comment by KN4CK3R** [comment]
Which compiler do you use?
