### ISSUE TITLE
No classes generated

### ISSUE THREAD

**Issue by yazzn** [KN4CK3R/UnrealEngineSDKGenerator#20]
I tried using the SDK Generator on Black Squad (UE3 free-to-play game on steam) and didn't get any good results thusfar.
All of the Packages just get skipped, NamesDump and ObjectsDump are getting generated however.
Here are the contents of [NamesDump.txt](https://gist.github.com/yazzn/307e3e7f058ed08a4a833b3b017395fc), [ObjectsDump.txt (partial cause my upload speed is trash)](https://gist.github.com/yazzn/d832279b3bcff073ce86cecb89febe9b)  and of Generator.log
> skip empty Package: C
> skip empty Package: E
> skip empty Package: GameFramework
> skip empty Package: Grip
> skip empty Package: Cognition
> skip empty Package: IpDrv
> skip empty Package: XAudio2
> skip empty Package: GFxUI
> skip empty Package: WinDrv
> skip empty Package: OnlineSubsystemPC
> skip empty Package: CombatGame
> skip empty Package: EngineResources
> skip empty Package: EngineMaterials
> skip empty Package: EngineMeshes
> skip empty Package: refshadercache-pc-d3d-sm3
> skip empty Package: ShadowBoundTest
> skip empty Package: CommonFx
> skip empty Package: S
> skip empty Package: CH_AnimTrees
> skip empty Package: CH_PhysicAsset
> skip empty Package: Materials
> skip empty Package: UIRT
> skip empty Package: CH_Animation
> skip empty Package: CombatPostProcess
> skip empty Package: CH_Animation_Inven
> skip empty Package: RandomBox
> skip empty Package: BackGroundFX
> skip empty Package: Effect_2017
> skip empty Package: CombatVolumetrics
> skip empty Package: ViewWeaponPhysicsBound
> skip empty Package: LevelObject
> skip empty Package: CBPhysicalMaterial
> skip empty Package: HitArea
> skip empty Package: ViewHandsPhysicsBound
> skip empty Package: Fonts
> skip empty Package: startup_loc
> skip empty Package: CH_Animation_JUG
> skip empty Package: T
> skip empty Package: combatgamecontent
> skip empty Package: RareFX
> skip empty Package: WP_Halloween
> skip empty Package: WP_CHRISTMAS
> skip empty Package: WP_PIS_SAIGlock17Tier1
> skip empty Package: WP_PIS_SV9
> skip empty Package: CM_Decal
> skip empty Package: Engine_MaterialFunctions01
> skip empty Package: CM_Tile
> skip empty Package: CubeMap
> skip empty Package: AttachmentFX
> skip empty Package: CM_Floor_A
> skip empty Package: CM_Nature
> skip empty Package: Engine_MI_Shaders
> skip empty Package: Engine_MaterialFunctions02
> skip empty Package: CM_Nature_A
> skip empty Package: CM_Ocean
> skip empty Package: Engine_MaterialFunctions03
> skip empty Package: WP_OPT_ScopeReticle
> skip empty Package: MO_C4
> skip empty Package: WP_OPT_Eotech
> skip empty Package: EQ_Rattler-H
> skip empty Package: SuperHind
> skip empty Package: EditorMaterials
> skip empty Package: TA_test
> skip empty Package: PREDATOR
> skip empty Package: WP_ARGL_M320
> skip empty Package: WP_Common_BulletCartridges
> skip empty Package: WP_OPT_Trijicon
> skip empty Package: WP_Parts_01
> skip empty Package: WP_Parts_02
> skip empty Package: startup
> skip empty Package: EngineSounds
> skip empty Package: PreLoadAsset
> skip empty Package: CharVox_Cue_F01
> skip empty Package: CharVox_Cue_F02
> skip empty Package: CharVox_Cue_M01
> skip empty Package: CharVox_Cue_M02
> skip empty Package: cpvox_cue_pm
> skip empty Package: cpvox_cue_vc
> skip empty Package: SoundClassesAndModes
> skip empty Package: Voice
> skip empty Package: Common
> skip empty Package: Font
> skip empty Package: CharVox_Wave_M01
> skip empty Package: CharVox_Wave_F01
> skip empty Package: CPVox_Wave_PM
> skip empty Package: CM_LUT
> skip empty Package: 33e8ee5d8d7aeb88a06e
> skip empty Package: WP_FSW_AT4
> skip empty Package: WP_SNI_M107A1
> skip empty Package: WP_DMR_SCAR-H
> skip empty Package: WP_FSW_M32
> skip empty Package: combatserverentry
> skip empty Package: FrontEnd_3D
> skip empty Package: LensFlare
> skip empty Package: CM_Deco_A
> skip empty Package: CM_Weapon
> skip empty Package: CM_Ext
> skip empty Package: CM_Furniture
> skip empty Package: CM_Crane
> skip empty Package: CM_Fence
> skip empty Package: CM_Wall
> skip empty Package: CM_Light
> skip empty Package: CM_Door
> skip empty Package: CM_Deco
> skip empty Package: CM_Box_barrel
> skip empty Package: CM_Floor
> skip empty Package: CM_Ceiling
> skip empty Package: CM_Wall_A
> skip empty Package: CM_Wall_B
> skip empty Package: LB_Brooklyn
> skip empty Package: CM_Unique_A
> skip empty Package: CM_Unique
> skip empty Package: FrontEnd_Rbox
> skip empty Package: CM_PhysicalMask
> skip empty Package: LB_Blitz
> skip empty Package: LB_Icicle
> skip empty Package: LB_TypeM
> skip empty Package: WP_DMR_SCAR-H_SKIN01
> skip empty Package: WP_DMR_SCAR-H_SKIN02
> skip empty Package: WP_OPT_Deltapoint
> skip empty Package: WP_OPT_Elcan
> skip empty Package: WP_OPT_LEUPOLD
> skip empty Package: WP_OPT_M32
> skip empty Package: WP_SNI_M107A1_SKIN01
> skip empty Package: WP_Melee_KukriPlatinum
> skip empty Package: LB_Sandsnake
> skip empty Package: BGM
> skip empty Package: FrontEnd
> skip empty Package: IME
> skip empty Package: UI_Effect
> skip empty Package: ItemIcon
> skip empty Package: VH_PM_Male
> skip empty Package: CH_VC01
> skip empty Package: VH_VC_Male
> skip empty Package: WP_AR_TAR21
> skip empty Package: WP_OPT_MeproM21
> Finished, took 0 seconds.

Is it possible that this is due to weirdly names classes like "C C.T", "C E.GameEngine" etc. or is it more likely because of potentially wrong offsets in EngineClasses.hpp?

Any advice is welcome.

**Comment by KN4CK3R** [comment]
Maybe the same issue like #16?

**Comment by yazzn** [comment]
I have tried it with Xenos' "Native Injection" and using manual mapping (with /MT switch)

**Comment by yazzn** [comment]
I managed to generate some structs by changing the names in [GenericTypes.hpp](https://gist.github.com/yazzn/47aea604bdbf14f6e9419e1af69772da)
Still no luck with classes/functions.

**Comment by yazzn** [comment]
The names are really weird. I could imagine that GetName is broken or something and it returns the AnsiName instead of WideName hence the {'C', '\0'}?

**Comment by yazzn** [comment]
Alright, I managed to dump it. If anyone else gets weird ass names try having `bool IsWide()` return either true or false only (depending on whether your game has wchar_t or char as `value_type`.

**Comment by KN4CK3R** [comment]
Good you got it working. Hawken uses widechars too sometimes: https://github.com/KN4CK3R/UnrealEngineSDKGenerator/blob/master/Target/Hawken/NamesStore.cpp

When you have finished your generator project you could make a pull request so everyone can use it. :)
