### ISSUE TITLE
'UObject::ProcessEvent': illegal call of non-static member function

### ISSUE THREAD

**Issue by yazzn** [KN4CK3R/UnrealEngineSDKGenerator#21]
Got the generator somewhat working the only issue remaining is that it generates a TON of functions that do not inherit from UObject hence `UObject::ProcessEvent` won't work there.

Any ideas as to how I can fix that?

**Comment by yazzn** [comment]
Got it to compile by replacing `UObject::ProcessEvent` with `static auto defaultObj = StaticClass()->CreateDefaultObject(); defaultObj->ProcessEvent`.
Not sure if that will allow me to call the functions but at least I got rid of the 17k errors.

**Comment by KN4CK3R** [comment]
Which classes don't inherit from UObject? Everything should inherit from it.

**Comment by yazzn** [comment]
Alright I fixed it by adding a UState class for everything that doesn't have a super class.
http://i.imgur.com/EUj85da.png

Not sure if that corrupts any class offsets but it surely makes the SDK compile cleanly.

**Comment by yazzn** [comment]
Also can you think of a cleaner way to replace duplicate enums other than doing it like this http://i.imgur.com/pb630SQ.png

**Comment by KN4CK3R** [comment]
UState: that should not work. Maybe the UState classes are getting removed again because they are only present in UnrealScript and have no C++ equivalent.

Enum: Doesn't https://github.com/KN4CK3R/UnrealEngineSDKGenerator/blob/master/Engine/Package.cpp#L307 do the job?
