### ISSUE TITLE
About PUBG sdk generation

### ISSUE THREAD

**Issue by zl950402** [KN4CK3R/UnrealEngineSDKGenerator#25]
everything is "skip empty Package" in log.

skip empty Package: CoreUObject
skip empty Package: TslGame
skip empty Package: Engine
skip empty Package: AIModule
skip empty Package: UMG
skip empty Package: OceanPlugin
skip empty Package: SlateCore
skip empty Package: CoherentUIGTPlugin
skip empty Package: EngineSettings
skip empty Package: CustomizableObject
skip empty Package: InputCore
skip empty Package: Slate

I haven't gen sdk in a month. anything updated?

**Comment by igromanru** [comment]
I really don't know what is you problem. The current state works without any changes needed.  
Also you can find the current SDK here
https://github.com/TJ888/PUBG-SDK
or here
https://github.com/pubgsdk/PUBG-SDK
