### ISSUE TITLE
Generated SDK adding to my project?

### ISSUE THREAD

**Issue by Salan56** [KN4CK3R/UnrealEngineSDKGenerator#27]
So I updated your SDK generator with the classes that I had reversed for my game and successfully generated an SDK,  however when I add the SDK to my project everything UE related that should be defined in the SDK is labled as Undefined by Visual Studio.  I am not sure what I am doing wrong.  I think I did everything correctly.  I added the SDK.hpp file and SDK folder into my project directory,  added SDK.hpp to includes in my project,  and even added all .cpp files from the SDK into my project just for safe measure.  Still anything and everything that should be defined in the sdk,  is not seen by Visual Studio in my project.  APawn myPawn;  <---- APawn is undefined.

Also in the SDK.hpp file I am seeing these includes and I am not sure what/where they are so I commented them out:

#include "../../Math/Vector3D.hpp"
#include "../../Math/Vector2D.hpp"

Can somebody help me please?

**Comment by KN4CK3R** [comment]
Fixed via PM. Forgot to use the namespace.
