### ISSUE TITLE
Fortnite FScriptDelegate size in Generator.cpp is incorrect and causes misalignment

### ISSUE THREAD

**Issue by TJ888** [KN4CK3R/UnrealEngineSDKGenerator#28]
Game Fortnite-
Inside Generator.cpp the following-
`struct FScriptDelegate
{
	char UnknownData[10];
};`

is supposed to be-
`struct FScriptDelegate
{
	char UnknownData[16];
};`

It is correct in EngineClass.hpp due to it being char UnknownData[0x10]; which is char UnknownData[16];

**Comment by KN4CK3R** [comment]
You could make a pull request. ;-)
