### ISSUE TITLE
RocketLeague ObjectsStore::Initialize failed

### ISSUE THREAD

**Issue by fredr121** [KN4CK3R/UnrealEngineSDKGenerator#30]
Rocket Leage SDK generator doesn't generate. Displays ObjectStore::Initialize failed right after injection. Maybe pattern doesn't work anymore or they now use some kind of encryption.

**Comment by TaylorSasser** [comment]
Works fine for all the mods i make

**Comment by fredr121** [comment]
I did a Debug build this time instead of a release build, now it works fine. I'm used to doing Release builds as they're faster if configured correctly. I'm using VS2017 ( v141 ) and Windows SDK version 10.0.15063.0. Probably it's just some optimization setting that would need to be changed for Release to work too.

**Comment by KN4CK3R** [comment]
I can't confirm that release builds don't work. I always use release builds after I'm sure the offsets are correct. Dumping with a debug build takes so much time.
