### ISSUE TITLE
Unresolved external symbol

### ISSUE THREAD

**Issue by daggemarren** [KN4CK3R/UnrealEngineSDKGenerator#33]
Hello, i've generated SDK for RocketLeague with your tool.

But when i use this code
`UGameEngine* pGameEngine = UObject::FindObject<UGameEngine>("GameEngine_TA Transient.GameEngine_TA_1");`

 i get this error

`Error	LNK2019	unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall SDK::UObject::GetFullName(void)const " (?GetFullName@UObject@SDK@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "public: static class SDK::UGameEngine * __cdecl SDK::UObject::FindObject<class SDK::UGameEngine>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$FindObject@VUGameEngine@SDK@@@UObject@SDK@@SAPAVUGameEngine@1@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	RocketLeague	C:\RocketLeague\test.obj	1	
`

I didnt get any error when generating the SDK, is there something i have done wrong?

**Comment by KN4CK3R** [comment]
Maybe you haven't added the needed .cpp files to your project?
See https://github.com/KN4CK3R/UnrealEngineSDKGenerator#and-now

**Comment by daggemarren** [comment]
Yes, now i have generated new SDK after recent update, and i get alot of 
Error	C2079	'SDK::FVOscillator::X' uses undefined struct 'SDK::FFOscillator'

**Comment by Quandissimo** [comment]
In the new update some of the generated struct are out of order, make sure to sort them out

**Comment by KN4CK3R** [comment]
Yes, you need to move the structs FNotificationInfo and FFOscillator above the structs which are using them. Currently I don't know if I can fix this problem.
