### ISSUE TITLE
Not work anymore with PUBG 2.6.46.7

### ISSUE THREAD

**Issue by deserwild** [KN4CK3R/UnrealEngineSDKGenerator#36]
Bluehole may put some trciks on their lastet game version. Game crashes immediately when generator dll injected to game.

**Comment by KN4CK3R** [comment]
I don't own PUBG but didn't they add xigncode and stuff? xigncode could prevent the dll injection.

**Comment by deserwild** [comment]
I'm pretty sure that the crash has nothing to do with xingcode3. The dll was injected successfully. Maybe GObject or some critical variables are encrypted.

**Comment by KN4CK3R** [comment]
looks like it's still working (not my screenshot)
