### ISSUE TITLE
Fortnite update 1.10 broke everything

### ISSUE THREAD

**Issue by TJ888** [KN4CK3R/UnrealEngineSDKGenerator#38]
This update seems to have changed quite a bit making it currently not dump correctly and instead just crash not even completing 1 single thing in the output file. The game is now packed, but I simply dumped it from memory and loaded it in IDA to check if the sigs are still working, and it turns out they are working, so they aren't the issue _I think_.

I tried debugging a little and it appears to crash whenever you loop over either GObjects OR GNames, and if you disable Dumping, it still crashes whenever it accesses the ObjectStore() with- GlobalObjects->ObjObjects.Objects Read Access Violation 0xFFFFFFFFFFFFFFFF.. 
If I debug it dumping GNames, this is the 1st name it gets- {Index=0 Name="h\b‚\x10ö" }, then it gets the 2nd Index which is also garbage, then crashes with an Access Violation Reading Location 0xFFFFFFFFFFFFFFFF when attempting to find the length of the null-terminating string.

Is it possible that they are now Encrypting GNames and GObjects? PUBG Is doing something similar with the AActor TArray where it is encrypted (broken within an hour though), or something else is wrong?

PS: Everything was attempted with BE and its driver completely Killed.

**Comment by KN4CK3R** [comment]
They have encrypted the names in the name array. GObjects looks normal but has some padding.

**Comment by KN4CK3R** [comment]
Updated the generator to work with the current v1.11.

**Comment by Hecklezz** [comment]
Nice work :)
