### ISSUE TITLE
UFunction->GetFullName Does not work

### ISSUE THREAD

**Issue by TaylorSasser** [KN4CK3R/UnrealEngineSDKGenerator#4]
I am able to successfully print out the Object names using feckless sdk generator and having the

FNameEntry  { 
	unsigned char	UnknownData00[ 0x10 ]; 
	char			Name[ 0x10 ]; 
}; 
setup like so.

When i try to do UFunction->GetFullName nothing works. Im not sure if the char* is different from a memory standpoint then a std::string and its not setup properly but something is wrong.

**Comment by KN4CK3R** [comment]
This is not Feckless' SDK generator. Which game are you talking about? If GetFullName does work for other objects it should work for functions too because there is no other logic.

**Comment by TaylorSasser** [comment]
Im saying, that when you have the struct FNameEntry setup like i posted, the 
get name functions work for Rocket league. I am aware that this is not the feckless, sorry if i was unclear.

**Comment by KN4CK3R** [comment]
But there is no code for Rocket League atm. As I said, you should make a pull request after you have created working code. No need to make a ticket for YOUR code (which we can't see).
