### ISSUE TITLE
ProcessEvent prototype might be wrong

### ISSUE THREAD

**Issue by rmadair** [KN4CK3R/UnrealEngineSDKGenerator#7]
Hi, so I noticed I was crashing on a lot of function calls. So I minimized to just a few lines of code:

```c++

pPlayerController = UObject::FindObject<APlayerController>("PlayerController_TA park_p.TheWorld.PersistentLevel.PlayerController_TA_1");
if (!pPlayerController)
	return false;

while (true)
{
	Sleep(500);
	std::cout << "team num -> " << pPlayerController->GetTeamNum() << '\n';
}
```

A little digging shows that the call to Sleep, is a dynamic call, in this case call ESI.

If you follow AController::GetTeamNum, it's prolog backs up 3 registers (push esi, push edi, push eax) and the stack looks like:

(start of function, right after push esi, push edi, push eax)
0:001> r
eax=1e203de7 ebx=629d7611 ecx=128f8c00 edx=00000000 esi=74e76770 edi=00ba0000
eip=003a3241 esp=1192feb8 ebp=1192fef0 iopl=0         nv up ei pl nz na pe nc
mymod!SDK::AController::GetTeamNum+0x21:
0:001> dd esp
1192feb8  1e203de7 00ba0000 74e76770 62a22d98
1192fec8  409fd301 1192ff3c 755e1c80 e3819dc7
1192fed8  fffffffe 1192feec 1e203de7 1192ff3c
1192fee8  003a4924 ffffffff 1192ff48 003a1803
 
Further down in the epilog, when the function goes to restore those registers (pop ecx, pop edi, pop esi), the stack looks like:
0:001> r
eax=193fb211 ebx=629d7611 ecx=1192ff3c edx=193fb280 esi=00020500 edi=128f8c00
eip=003a3335 esp=1192febc ebp=1192fef0 iopl=0         nv up ei pl zr na pe nc
mymod!SDK::AController::GetTeamNum+0x115:
0:001> dd esp
1192febc  00ba0000 74e76770 62a22d98 409fd301
1192fecc  1192ff3c 755e1c80 e3819dc7 fffffffe
1192fedc  1192feec 1e203de7 1192ff3c 003a4924
1192feec  ffffffff 1192ff48 003a1803 1e203c5f

The stack is off by 4 bytes. Adjusting it fixes the issue:
0:001> dd esp-4
1192feb8  1e203de7 00ba0000 74e76770 62a22d98
1192fec8  409fd301 1192ff3c 755e1c80 e3819dc7
1192fed8  fffffffe 1192feec 1e203de7 1192ff3c
0:001> r esp=@esp-4
0:001> g  <--- works just fine

A little further digging showed the last dynamic call in the AController::GetTeamNum, call eax (which in the source is UObject::ProcessEvent(fn, &params);) is only taking 2 params. But the return of this function is ret 0xC. It looks like ProcessEvent needs to take a 3rd argument (which matches up with the results from dd esp-4 from above).

I know the SDK claims the prototype is virtual void ProcessEvent (UFunction * Function, void * Parms), but the stack is off by 4, and there is a ret 0xc instead of 0x8. Also, a quick look in IDA at this function (image base + offset 0x002b5f20) shows the prototype as int __thiscall sub_6B5F20(_DWORD *this, int a2, void *Src, int a4). So it's showing 3 arguments as well.

Since ProcessEvent is called all over the place in the SDK, I can't do much without triggering this issue.

Any help is appreciated, I hope the above makes it easy to identify on your end.

Thanks!

**Comment by KN4CK3R** [comment]
Which game?

**Comment by rmadair** [comment]
Oops, sorry! This is for Rocket League. (btw thanks for the quick update :))

**Comment by TaylorSasser** [comment]
How are you hooking the process event?

**Comment by rmadair** [comment]
@TaylorSasser 

I'm not, my code is literally just:

```C++

// initialize
// get pGameEngine
// get pPlayerController

while (true) 
{ 
    Sleep(500); 
    std::cout << "team num -> " << pPlayerController->GetTeamNum() << '\n'; 
}
```

The issue is AController::GetTeamNum ends up calling UObject::ProcessEvent. In the compiled code it's actually a `call eax`. That function does a `ret 0xc` at the end, but only 2 arguments (0x8 bytes) were passed to it. So the stack becomes off by 4 bytes.

I'm not manually calling, hooking, or otherwise doing anything with ProcessEvent. Just calling GetTeamNum. Some functions that don't end up calling ProcessEvent work just fine. Like I can get the car's location just fine with `printf("X: %.3f Y: %.3f Z: %.3f\n", pPlayerController->Pawn->Location.X, pPlayerController->Pawn->Location.Y, pPlayerController->Pawn->Location.Z);`

**Comment by rmadair** [comment]
Actually, just a little more supporting evidence. If you grab Janck7's SDK (https://www.unknowncheats.me/forum/other-fps-games/179108-rocket-league-sdk-reversing-information.html) and check out his GetTeamNum function:

```C++
unsigned char ATeamInfo::GetTeamNum ( )
{
    static UFunction* pFnGetTeamNum = NULL;

    if ( ! pFnGetTeamNum )
        pFnGetTeamNum = (UFunction*) UObject::GObjObjects()->Data[ 33925 ];
    ATeamInfo_execGetTeamNum_Parms GetTeamNum_Parms;
    pFnGetTeamNum->FunctionFlags |= ~0x400;
    this->ProcessEvent ( pFnGetTeamNum, &GetTeamNum_Parms, NULL );    // <------ 3 params
    pFnGetTeamNum->FunctionFlags |= 0x400; 
    return GetTeamNum_Parms.ReturnValue;
};
```

He's calling ProcessEvent, and it has a 3rd argument as well. Looks like that might be the fix.

**Comment by TaylorSasser** [comment]
Yea, but this was never a problem in the last update so something changed.

**Comment by rmadair** [comment]
Adding the 3rd argument indeed fixed the issue. I created a pull request.
